// Code generated by internal/product/gen from product.json. DO NOT EDIT.

package product

const (
	// Name is the human-readable product name.
	Name = "Dati Monitor"
	// Slug is the lowercase identifier used in Linux paths and package names.
	Slug = "dati-monitor"
	// ServicePrefix is the prefix of Windows service names and Windows folders.
	ServicePrefix = "DatiMonitor"
)
