"""coletor desinstalado

Revision ID: c82965fbc181
Revises: 72aef375bf43
Create Date: 2026-10-07 00:24:36.995252+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c82965fbc181'
down_revision: str | None = '72aef375bf43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Tipo novo de regra: o autogenerate não vê mudança na lista do CHECK.
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open', 'jam_recurrent', 'printer_alert', 'agent_uninstalled')")


def downgrade() -> None:
    op.execute("DELETE FROM alert_rules WHERE type = 'agent_uninstalled'")
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open', 'jam_recurrent', 'printer_alert')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'uninstalled_at')
    # ### end Alembic commands ###
