"""fase 5.1 auditoria datacount: descobertas, reading_counters, trocas de toner, alertas da impressora,
cadastro e atributos do equipamento, endereço do local, opções do coletor e matriz de permissões.

Revision ID: 11f512d72613
Revises: d02be972f55c
Create Date: 2026-09-29 01:28:20.224727+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "11f512d72613"
down_revision: str | None = "d02be972f55c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_field_definitions",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("field_type", sa.String(length=16), server_default=sa.text("'text'"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "field_type IN ('text', 'number', 'date')",
            name=op.f("ck_custom_field_definitions_field_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_custom_field_definitions_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field_definitions")),
        sa.UniqueConstraint("reseller_id", "key", name=op.f("uq_custom_field_definitions_reseller_id_key")),
    )
    op.create_index(
        op.f("ix_custom_field_definitions_reseller_id"),
        "custom_field_definitions",
        ["reseller_id"],
        unique=False,
    )
    op.create_table(
        "reseller_role_permissions",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["reseller_id"],
            ["resellers.id"],
            name=op.f("fk_reseller_role_permissions_reseller_id_resellers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_code"],
            ["roles.code"],
            name=op.f("fk_reseller_role_permissions_role_code_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_reseller_role_permissions_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("reseller_id", "role_code", name=op.f("pk_reseller_role_permissions")),
    )
    op.create_table(
        "device_attribute_snapshots",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_attribute_snapshots_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"],
            ["resellers.id"],
            name=op.f("fk_device_attribute_snapshots_reseller_id_resellers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_attribute_snapshots")),
    )
    op.create_index(
        "ix_device_attribute_snapshots_device_id_read_at",
        "device_attribute_snapshots",
        ["device_id", sa.literal_column("read_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_attribute_snapshots_reseller_id"),
        "device_attribute_snapshots",
        ["reseller_id"],
        unique=False,
    )
    op.create_table(
        "printer_alerts",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("alert_key", sa.String(length=64), nullable=False),
        sa.Column("prt_index", sa.Integer(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("training_level", sa.Integer(), nullable=True),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("group_index", sa.Integer(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=True),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("alert_time_ticks", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_at", sa.BigInteger(), nullable=True),
        sa.Column("mono_at", sa.BigInteger(), nullable=True),
        sa.Column("color_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('parts', 'service_call', 'jam', 'consumable', 'other')",
            name=op.f("ck_printer_alerts_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_printer_alerts_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_printer_alerts_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printer_alerts")),
    )
    op.create_index(
        "ix_printer_alerts_device_id_first_seen_at",
        "printer_alerts",
        ["device_id", "first_seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_printer_alerts_reseller_id_category_first_seen_at",
        "printer_alerts",
        ["reseller_id", "category", "first_seen_at"],
        unique=False,
    )
    op.create_index(
        "uq_printer_alerts_device_id_alert_key_active",
        "printer_alerts",
        ["device_id", "alert_key"],
        unique=True,
        postgresql_where=sa.text("cleared_at IS NULL"),
    )
    op.create_table(
        "reading_counters",
        sa.Column("reading_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("color_mode", sa.String(length=16), nullable=False),
        sa.Column("size", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "color_mode IN ('mono', 'full_color', 'single_color', 'two_color', 'any')",
            name=op.f("ck_reading_counters_color_mode_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('total', 'print', 'copy', 'fax', 'scan', 'report', 'duplex', 'other')",
            name=op.f("ck_reading_counters_kind_valid"),
        ),
        sa.CheckConstraint(
            "size IN ('a3', 'a4', 'letter', 'legal', 'other', 'any')",
            name=op.f("ck_reading_counters_size_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_reading_counters_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_reading_counters_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint(
            "reading_id", "read_at", "kind", "color_mode", "size", name=op.f("pk_reading_counters")
        ),
        postgresql_partition_by="RANGE (read_at)",
    )
    op.create_index(
        "ix_reading_counters_device_id_read_at", "reading_counters", ["device_id", "read_at"], unique=False
    )
    op.create_table(
        "supply_replacements",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("supply_key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("supply_type", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level_before", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("level_after", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("total_before", sa.BigInteger(), nullable=True),
        sa.Column("mono_before", sa.BigInteger(), nullable=True),
        sa.Column("color_before", sa.BigInteger(), nullable=True),
        sa.Column("total_after", sa.BigInteger(), nullable=True),
        sa.Column("mono_after", sa.BigInteger(), nullable=True),
        sa.Column("color_after", sa.BigInteger(), nullable=True),
        sa.Column("yield_pages", sa.BigInteger(), nullable=True),
        sa.Column("yield_counter", sa.String(length=8), nullable=True),
        sa.Column("previous_replacement_id", sa.UUID(), nullable=True),
        sa.Column("nominal_capacity", sa.Integer(), nullable=True),
        sa.Column("premature", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cartridge_serial_before", sa.String(length=128), nullable=True),
        sa.Column("cartridge_serial_after", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "yield_counter IN ('total', 'color')", name=op.f("ck_supply_replacements_yield_counter_valid")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_supply_replacements_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["previous_replacement_id"],
            ["supply_replacements.id"],
            name=op.f("fk_supply_replacements_previous_replacement_id_supply_replacements"),
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_supply_replacements_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supply_replacements")),
    )
    op.create_index(
        "ix_supply_replacements_device_id_supply_key_replaced_at",
        "supply_replacements",
        ["device_id", "supply_key", "replaced_at"],
        unique=False,
    )
    op.create_index(
        "ix_supply_replacements_reseller_id_replaced_at",
        "supply_replacements",
        ["reseller_id", "replaced_at"],
        unique=False,
    )
    op.add_column(
        "agents",
        sa.Column("monitor_local_networks", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("agents", sa.Column("public_ip", sa.String(length=64), nullable=True))
    op.add_column("agents", sa.Column("install_path", sa.Text(), nullable=True))
    op.add_column(
        "customers",
        sa.Column("toner_monitoring", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "customers",
        sa.Column(
            "toner_thresholds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'{"black": 10, "cyan": 10, "magenta": 10, "yellow": 10}\'::jsonb'),
            nullable=False,
        ),
    )
    # Equipamentos que já existiam estavam no parque: entram aprovados; os novos passam a nascer pendentes.
    op.add_column(
        "devices",
        sa.Column(
            "discovery_state", sa.String(length=16), server_default=sa.text("'approved'"), nullable=False
        ),
    )
    op.alter_column("devices", "discovery_state", server_default=sa.text("'pending'"))
    op.create_check_constraint(
        "discovery_state_valid", "devices", "discovery_state IN ('pending', 'approved', 'discarded')"
    )
    op.add_column("devices", sa.Column("discovery_decided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("devices", sa.Column("discovery_decided_by", sa.UUID(), nullable=True))
    op.add_column("devices", sa.Column("alt_serial", sa.String(length=128), nullable=True))
    op.add_column("devices", sa.Column("sys_location", sa.String(length=255), nullable=True))
    op.add_column(
        "devices", sa.Column("sector_from_snmp", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    op.execute(
        "UPDATE devices SET sector_from_snmp = false WHERE sector IS NOT NULL"
    )  # setor digitado no portal
    op.add_column("devices", sa.Column("franchise_value", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column("devices", sa.Column("franchise_pages_mono", sa.Integer(), nullable=True))
    op.add_column("devices", sa.Column("franchise_pages_color", sa.Integer(), nullable=True))
    op.add_column(
        "devices", sa.Column("overage_price_mono", sa.Numeric(precision=10, scale=4), nullable=True)
    )
    op.add_column(
        "devices", sa.Column("overage_price_color", sa.Numeric(precision=10, scale=4), nullable=True)
    )
    op.add_column(
        "devices",
        sa.Column(
            "custom_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "devices",
        sa.Column("toner_mode", sa.String(length=16), server_default=sa.text("'global'"), nullable=False),
    )
    op.create_check_constraint("toner_mode_valid", "devices", "toner_mode IN ('off', 'global', 'individual')")
    op.add_column(
        "devices",
        sa.Column(
            "toner_thresholds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "devices",
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("devices", sa.Column("attributes_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_devices_reseller_id_discovery_state", "devices", ["reseller_id", "discovery_state"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_devices_discovery_decided_by_users"), "devices", "users", ["discovery_decided_by"], ["id"]
    )
    op.add_column("ip_ranges", sa.Column("host", sa.String(length=255), nullable=True))
    op.add_column("sites", sa.Column("cep", sa.String(length=8), nullable=True))
    op.add_column("sites", sa.Column("street", sa.String(length=300), nullable=True))
    op.add_column("sites", sa.Column("number", sa.String(length=30), nullable=True))
    op.add_column("sites", sa.Column("complement", sa.String(length=200), nullable=True))
    op.add_column("sites", sa.Column("district", sa.String(length=200), nullable=True))
    op.add_column("sites", sa.Column("city", sa.String(length=200), nullable=True))
    op.add_column("sites", sa.Column("state", sa.String(length=2), nullable=True))
    op.add_column("sites", sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column("sites", sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column(
        "sites",
        sa.Column("auto_activate_devices", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.execute("UPDATE sites SET street = left(address, 300) WHERE address IS NOT NULL")
    op.drop_column("sites", "address")
    op.add_column("supplies_current", sa.Column("cartridge_serial", sa.String(length=128), nullable=True))
    op.add_column(
        "supplies_current", sa.Column("days_to_empty_min", sa.Numeric(precision=8, scale=1), nullable=True)
    )
    op.add_column(
        "supplies_current", sa.Column("days_to_empty_max", sa.Numeric(precision=8, scale=1), nullable=True)
    )
    op.add_column("supplies_current", sa.Column("pages_left", sa.BigInteger(), nullable=True))
    op.add_column("supplies_current", sa.Column("forecast_method", sa.String(length=16), nullable=True))
    op.add_column(
        "supplies_current", sa.Column("forecast_confidence", sa.Numeric(precision=4, scale=3), nullable=True)
    )
    op.add_column("supply_readings", sa.Column("cartridge_serial", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###
    _reading_counters_sql()
    # Tipos novos de evento: ativado/descartado/restaurado em Descobertas e troca de suprimento.
    op.drop_constraint(op.f("ck_device_events_type_valid"), "device_events", type_="check")
    op.create_check_constraint(
        "type_valid",
        "device_events",
        "type IN ('discovered', 'ip_changed', 'moved_site', 'replaced', 'counter_regression', 'reactivated', 'deactivated', 'manual_adjust', 'read_failed', 'suspicious_jump', 'sum_mismatch', 'reading_discarded', 'reading_classified', 'approved', 'discarded', 'restored', 'supply_replaced')",
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM device_events WHERE type IN ('approved', 'discarded', 'restored', 'supply_replaced')"
    )
    op.drop_constraint(op.f("ck_device_events_type_valid"), "device_events", type_="check")
    op.create_check_constraint(
        "type_valid",
        "device_events",
        "type IN ('discovered', 'ip_changed', 'moved_site', 'replaced', 'counter_regression', 'reactivated', 'deactivated', 'manual_adjust', 'read_failed', 'suspicious_jump', 'sum_mismatch', 'reading_discarded', 'reading_classified')",
    )
    op.execute(
        _PARTITION_FUNCTION_SQL.replace(
            "'readings', 'reading_counters', 'audit_log'", "'readings', 'audit_log'"
        )
    )
    op.drop_constraint(op.f("ck_devices_discovery_state_valid"), "devices", type_="check")
    op.drop_constraint(op.f("ck_devices_toner_mode_valid"), "devices", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supply_readings", "cartridge_serial")
    op.drop_column("supplies_current", "forecast_confidence")
    op.drop_column("supplies_current", "forecast_method")
    op.drop_column("supplies_current", "pages_left")
    op.drop_column("supplies_current", "days_to_empty_max")
    op.drop_column("supplies_current", "days_to_empty_min")
    op.drop_column("supplies_current", "cartridge_serial")
    op.add_column("sites", sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("UPDATE sites SET address = street")
    op.drop_column("sites", "auto_activate_devices")
    op.drop_column("sites", "longitude")
    op.drop_column("sites", "latitude")
    op.drop_column("sites", "state")
    op.drop_column("sites", "city")
    op.drop_column("sites", "district")
    op.drop_column("sites", "complement")
    op.drop_column("sites", "number")
    op.drop_column("sites", "street")
    op.drop_column("sites", "cep")
    op.drop_column("ip_ranges", "host")
    op.drop_constraint(op.f("fk_devices_discovery_decided_by_users"), "devices", type_="foreignkey")
    op.drop_index("ix_devices_reseller_id_discovery_state", table_name="devices")
    op.drop_column("devices", "attributes_at")
    op.drop_column("devices", "attributes")
    op.drop_column("devices", "toner_thresholds")
    op.drop_column("devices", "toner_mode")
    op.drop_column("devices", "custom_fields")
    op.drop_column("devices", "overage_price_color")
    op.drop_column("devices", "overage_price_mono")
    op.drop_column("devices", "franchise_pages_color")
    op.drop_column("devices", "franchise_pages_mono")
    op.drop_column("devices", "franchise_value")
    op.drop_column("devices", "sector_from_snmp")
    op.drop_column("devices", "sys_location")
    op.drop_column("devices", "alt_serial")
    op.drop_column("devices", "discovery_decided_by")
    op.drop_column("devices", "discovery_decided_at")
    op.drop_column("devices", "discovery_state")
    op.drop_column("customers", "toner_thresholds")
    op.drop_column("customers", "toner_monitoring")
    op.drop_column("agents", "install_path")
    op.drop_column("agents", "public_ip")
    op.drop_column("agents", "monitor_local_networks")
    op.drop_index("ix_supply_replacements_reseller_id_replaced_at", table_name="supply_replacements")
    op.drop_index("ix_supply_replacements_device_id_supply_key_replaced_at", table_name="supply_replacements")
    op.drop_table("supply_replacements")
    op.drop_index("ix_reading_counters_device_id_read_at", table_name="reading_counters")
    op.execute("SET LOCAL dati.maintenance = 'on'")
    op.drop_table("reading_counters")
    op.execute("SET LOCAL dati.maintenance = 'off'")
    op.drop_index(
        "uq_printer_alerts_device_id_alert_key_active",
        table_name="printer_alerts",
        postgresql_where=sa.text("cleared_at IS NULL"),
    )
    op.drop_index("ix_printer_alerts_reseller_id_category_first_seen_at", table_name="printer_alerts")
    op.drop_index("ix_printer_alerts_device_id_first_seen_at", table_name="printer_alerts")
    op.drop_table("printer_alerts")
    op.drop_index(op.f("ix_device_attribute_snapshots_reseller_id"), table_name="device_attribute_snapshots")
    op.drop_index("ix_device_attribute_snapshots_device_id_read_at", table_name="device_attribute_snapshots")
    op.drop_table("device_attribute_snapshots")
    op.drop_table("reseller_role_permissions")
    op.drop_index(op.f("ix_custom_field_definitions_reseller_id"), table_name="custom_field_definitions")
    op.drop_table("custom_field_definitions")
    # ### end Alembic commands ###


# Mapeamento padrão dos contadores normalizados para linhas (cópia congelada de
# app.services.counter_lines.DEFAULT_LINES no momento desta migração).
_DEFAULT_LINES = (
    ("total", "total", "any", "any"),
    ("mono", "total", "mono", "any"),
    ("color", "total", "full_color", "any"),
    ("mono_large", "total", "mono", "a3"),
    ("color_large", "total", "full_color", "a3"),
    ("copy_total", "copy", "any", "any"),
    ("copy_mono", "copy", "mono", "any"),
    ("copy_color", "copy", "full_color", "any"),
    ("print_total", "print", "any", "any"),
    ("print_mono", "print", "mono", "any"),
    ("print_color", "print", "full_color", "any"),
    ("scan", "scan", "any", "any"),
    ("fax", "fax", "any", "any"),
    ("duplex", "duplex", "any", "any"),
)
_COLUMNS = (
    "total",
    "mono",
    "color",
    "mono_large",
    "color_large",
    "copy_mono",
    "copy_color",
    "print_mono",
    "print_color",
    "scan",
    "fax",
)

_PARTITION_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION dm_ensure_month_partition(parent text, key_column text, month_start date)
RETURNS boolean
LANGUAGE plpgsql AS $$
DECLARE
    first_day date := date_trunc('month', month_start)::date;
    next_day date := (date_trunc('month', month_start) + interval '1 month')::date;
    part text := parent || '_' || to_char(first_day, 'YYYY_MM');
    def text := parent || '_default';
    lo text := to_char(first_day, 'YYYY-MM-DD') || ' 00:00:00+00';
    hi text := to_char(next_day, 'YYYY-MM-DD') || ' 00:00:00+00';
BEGIN
    IF to_regclass(part) IS NOT NULL THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TABLE %I (LIKE %I INCLUDING DEFAULTS INCLUDING CONSTRAINTS)', part, parent);
    IF to_regclass(def) IS NOT NULL THEN
        PERFORM set_config('dati.maintenance', 'on', true);
        EXECUTE format(
            'WITH moved AS (DELETE FROM %I WHERE %I >= %L AND %I < %L RETURNING *) INSERT INTO %I SELECT * FROM moved',
            def, key_column, lo, key_column, hi, part
        );
        PERFORM set_config('dati.maintenance', 'off', true);
    END IF;
    EXECUTE format('ALTER TABLE %I ATTACH PARTITION %I FOR VALUES FROM (%L) TO (%L)', parent, part, lo, hi);
    IF parent IN ('readings', 'reading_counters', 'audit_log') THEN
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()',
            part || '_no_truncate', part
        );
    END IF;
    RETURN true;
END;
$$;
"""


def _reading_counters_sql() -> None:
    """Partições e bloqueio de alteração de reading_counters, e as linhas das leituras que já existiam."""
    op.execute(_PARTITION_FUNCTION_SQL)
    op.execute(
        "CREATE TRIGGER reading_counters_append_only BEFORE UPDATE OR DELETE ON reading_counters "
        "FOR EACH ROW EXECUTE FUNCTION dm_block_modification()"
    )
    op.execute(
        "CREATE TRIGGER reading_counters_no_truncate BEFORE TRUNCATE ON reading_counters "
        "FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()"
    )
    op.execute("CREATE TABLE reading_counters_default PARTITION OF reading_counters DEFAULT")
    op.execute(
        "CREATE TRIGGER reading_counters_default_no_truncate BEFORE TRUNCATE ON reading_counters_default "
        "FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()"
    )
    # Os meses que readings já tem e a janela padrão (o worker mantém a janela andando).
    op.execute(
        "SELECT dm_ensure_month_partition('reading_counters', 'read_at', m::date) FROM ("
        "  SELECT DISTINCT date_trunc('month', read_at) AS m FROM readings"
        "  UNION SELECT date_trunc('month', now()) + make_interval(months => g) FROM generate_series(-1, 3) g"
        ") months"
    )
    lines = ", ".join(f"('{n}', '{k}', '{c}', '{z}')" for n, k, c, z in _DEFAULT_LINES)
    cols = " UNION ALL ".join(
        f"SELECT '{c}' AS name, r.{c} AS value WHERE r.{c} IS NOT NULL" for c in _COLUMNS
    )
    op.execute(
        "INSERT INTO reading_counters "
        "(reading_id, read_at, reseller_id, device_id, kind, color_mode, size, name, value) "
        "SELECT DISTINCT ON (r.id, r.read_at, m.kind, m.color_mode, m.size) "
        "  r.id, r.read_at, r.reseller_id, r.device_id, m.kind, m.color_mode, m.size, m.name, v.value "
        "FROM readings r "
        "CROSS JOIN LATERAL ("
        f"  {cols} UNION ALL "
        "  SELECT e.key, e.value::bigint FROM jsonb_each_text(coalesce(r.extra -> 'counters', '{}'::jsonb)) e "
        "  WHERE e.value ~ '^-?[0-9]{1,18}$'"
        ") v "
        f"JOIN (VALUES {lines}) AS m(name, kind, color_mode, size) ON m.name = v.name "  # noqa: S608 - constantes
        "ORDER BY r.id, r.read_at, m.kind, m.color_mode, m.size"
    )
