"""fase 8 instaladores

Revision ID: 72aef375bf43
Revises: 8fa8ef64d498
Create Date: 2026-10-02 14:58:18.885002+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '72aef375bf43'
down_revision: str | None = '8fa8ef64d498'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installers',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('arch', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('withdrawn', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("arch IN ('all', 'amd64', '386', 'arm64', 'arm')", name=op.f('ck_installers_arch_valid')),
    sa.CheckConstraint("kind IN ('windows', 'deb', 'tar')", name=op.f('ck_installers_kind_valid')),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_installers_published_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installers')),
    sa.UniqueConstraint('kind', 'arch', 'version', name=op.f('uq_installers_kind_arch_version'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installers')
    # ### end Alembic commands ###
