"""historico de cliente do equipamento

Revision ID: 054547c6c601
Revises: c82965fbc181
Create Date: 2026-10-07 00:31:05.170435+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '054547c6c601'
down_revision: str | None = 'c82965fbc181'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_assignments',
    sa.Column('reseller_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_device_assignments_customer_id_customers')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_assignments_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], name=op.f('fk_device_assignments_reseller_id_resellers')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_device_assignments_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_assignments'))
    )
    op.create_index('ix_device_assignments_customer_id', 'device_assignments', ['customer_id'], unique=False)
    op.create_index('ix_device_assignments_device_id_start_at', 'device_assignments', ['device_id', 'start_at'], unique=False)
    op.add_column('devices', sa.Column('transfer_site_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('transfer_detected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('transfer_ignored_site_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_devices_transfer_site_id_sites'), 'devices', 'sites', ['transfer_site_id'], ['id'])
    op.create_foreign_key(op.f('fk_devices_transfer_ignored_site_id_sites'), 'devices', 'sites', ['transfer_ignored_site_id'], ['id'])
    # ### end Alembic commands ###
    # Histórico inicial: cada equipamento está no cliente/local atual "desde sempre".
    op.execute(
        "INSERT INTO device_assignments (id, reseller_id, device_id, customer_id, site_id, start_at) "
        "SELECT gen_random_uuid(), reseller_id, id, customer_id, site_id, TIMESTAMPTZ '1970-01-01 00:00:00+00' "
        "FROM devices"
    )
    # Listas de CHECK (o autogenerate não vê): eventos e tipo de regra novos.
    op.drop_constraint(op.f("ck_device_events_type_valid"), "device_events", type_="check")
    op.create_check_constraint(
        "type_valid",
        "device_events",
        "type IN ('discovered', 'ip_changed', 'moved_site', 'replaced', 'counter_regression', 'reactivated', 'deactivated', 'manual_adjust', 'read_failed', 'suspicious_jump', 'sum_mismatch', 'reading_discarded', 'reading_classified', 'approved', 'discarded', 'restored', 'supply_replaced', 'transfer_detected', 'transfer_approved', 'transfer_rejected')",
    )
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open', 'jam_recurrent', 'printer_alert', 'agent_uninstalled', 'device_transfer')")


def downgrade() -> None:
    op.execute("DELETE FROM alert_rules WHERE type = 'device_transfer'")
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open', 'jam_recurrent', 'printer_alert', 'agent_uninstalled')")
    op.execute("DELETE FROM device_events WHERE type IN ('transfer_detected', 'transfer_approved', 'transfer_rejected')")
    op.drop_constraint(op.f("ck_device_events_type_valid"), "device_events", type_="check")
    op.create_check_constraint("type_valid", "device_events", "type IN ('discovered', 'ip_changed', 'moved_site', 'replaced', 'counter_regression', 'reactivated', 'deactivated', 'manual_adjust', 'read_failed', 'suspicious_jump', 'sum_mismatch', 'reading_discarded', 'reading_classified', 'approved', 'discarded', 'restored', 'supply_replaced')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_transfer_ignored_site_id_sites'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('fk_devices_transfer_site_id_sites'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'transfer_ignored_site_id')
    op.drop_column('devices', 'transfer_detected_at')
    op.drop_column('devices', 'transfer_site_id')
    op.drop_index('ix_device_assignments_device_id_start_at', table_name='device_assignments')
    op.drop_index('ix_device_assignments_customer_id', table_name='device_assignments')
    op.drop_table('device_assignments')
    # ### end Alembic commands ###
