"""esquema inicial: todas as tabelas da seção 3, partições mensais e triggers somente-inserção

Revision ID: aadbb17b4720
Revises:
Create Date: 2026-09-24 17:25:17.199337+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "aadbb17b4720"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enterprise_id", sa.Integer(), nullable=True),
        sa.Column("sys_object_id_prefix", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name=op.f("uq_brands_name")),
    )
    op.create_table(
        "reading_idempotency",
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("reading_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_reading_idempotency")),
    )
    op.create_table(
        "resellers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resellers")),
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_roles")),
    )
    op.create_table(
        "companies",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_companies_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_reseller_id"), "companies", ["reseller_id"], unique=False)
    op.create_table(
        "notification_channels",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("config_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('email', 'whatsapp', 'webhook')", name=op.f("ck_notification_channels_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_notification_channels_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
    )
    op.create_index(
        op.f("ix_notification_channels_reseller_id"), "notification_channels", ["reseller_id"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("permission", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_code"],
            ["roles.code"],
            name=op.f("fk_role_permissions_role_code_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_code", "permission", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "settings",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value_enc", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_settings_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("reseller_id", "key", name=op.f("uq_settings_reseller_id_key")),
    )
    op.create_table(
        "customers",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("erp_code", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_customers_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_customers_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_company_id"), "customers", ["company_id"], unique=False)
    op.create_index(op.f("ix_customers_reseller_id"), "customers", ["reseller_id"], unique=False)
    op.create_index(
        "uq_customers_reseller_erp_code",
        "customers",
        ["reseller_id", "erp_code"],
        unique=True,
        postgresql_where=sa.text("erp_code IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "alert_rules",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=16), server_default=sa.text("'warning'"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "channel_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_alert_rules_severity_valid")
        ),
        sa.CheckConstraint(
            "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open')",
            name=op.f("ck_alert_rules_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_alert_rules_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_alert_rules_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index(op.f("ix_alert_rules_customer_id"), "alert_rules", ["customer_id"], unique=False)
    op.create_index(op.f("ix_alert_rules_reseller_id"), "alert_rules", ["reseller_id"], unique=False)
    op.create_table(
        "sites",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "timezone", sa.String(length=64), server_default=sa.text("'America/Sao_Paulo'"), nullable=False
        ),
        sa.Column(
            "collection_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("master_agent_id", sa.UUID(), nullable=True),
        sa.Column("preferred_master_agent_id", sa.UUID(), nullable=True),
        sa.Column("master_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_sites_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_sites_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
    )
    op.create_index(op.f("ix_sites_customer_id"), "sites", ["customer_id"], unique=False)
    op.create_index(op.f("ix_sites_reseller_id"), "sites", ["reseller_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_code", sa.String(length=32), nullable=False),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_users_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_users_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["role_code"], ["roles.code"], name=op.f("fk_users_role_code_roles")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_customer_id"), "users", ["customer_id"], unique=False)
    op.create_index(op.f("ix_users_reseller_id"), "users", ["reseller_id"], unique=False)
    op.create_index(
        "uq_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "agent_releases",
        sa.Column("component", sa.String(length=16), server_default=sa.text("'agent'"), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("os", sa.String(length=16), nullable=False),
        sa.Column("arch", sa.String(length=16), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rollout_percent", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("yanked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('canary', 'stable')", name=op.f("ck_agent_releases_channel_valid")),
        sa.CheckConstraint(
            "component IN ('agent', 'watchdog')", name=op.f("ck_agent_releases_component_valid")
        ),
        sa.ForeignKeyConstraint(
            ["published_by"], ["users.id"], name=op.f("fk_agent_releases_published_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_releases")),
        sa.UniqueConstraint(
            "component", "version", "os", "arch", name=op.f("uq_agent_releases_component_version_os_arch")
        ),
    )
    op.create_table(
        "agents",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default=sa.text("'windows'"), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("arch", sa.String(length=32), nullable=True),
        sa.Column(
            "local_ips",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("host_mac", sa.String(length=32), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("watchdog_version", sa.String(length=64), nullable=True),
        sa.Column("update_channel", sa.String(length=16), server_default=sa.text("'stable'"), nullable=False),
        sa.Column("cluster_role", sa.String(length=16), server_default=sa.text("'standby'"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("state", sa.String(length=16), server_default=sa.text("'offline'"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_watchdog_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("secret_hash", sa.String(length=128), nullable=True),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("config_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("applied_config_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("queue_pending", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("uptime_seconds", sa.BigInteger(), nullable=True),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("avg_latency_ms", sa.Float(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "suggested_ranges",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cluster_role IN ('master', 'standby')", name=op.f("ck_agents_cluster_role_valid")
        ),
        sa.CheckConstraint("kind IN ('windows', 'linux')", name=op.f("ck_agents_kind_valid")),
        sa.CheckConstraint(
            "state IN ('online', 'offline', 'degraded', 'paused')", name=op.f("ck_agents_state_valid")
        ),
        sa.CheckConstraint(
            "update_channel IN ('canary', 'stable')", name=op.f("ck_agents_update_channel_valid")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_agents_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_agents_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_foreign_key("fk_sites_master_agent_id_agents", "sites", "agents", ["master_agent_id"], ["id"])
    op.create_foreign_key(
        "fk_sites_preferred_master_agent_id_agents", "sites", "agents", ["preferred_master_agent_id"], ["id"]
    )
    op.create_index(op.f("ix_agents_reseller_id"), "agents", ["reseller_id"], unique=False)
    op.create_index("ix_agents_site_id_cluster_role", "agents", ["site_id", "cluster_role"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("dedup_key", sa.String(length=300), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_alerts_severity_valid")
        ),
        sa.CheckConstraint(
            "state IN ('open', 'acknowledged', 'resolved')", name=op.f("ck_alerts_state_valid")
        ),
        sa.CheckConstraint(
            "target_type IN ('device', 'agent', 'site')", name=op.f("ck_alerts_target_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_alerts_acknowledged_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_alerts_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_alerts_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], name=op.f("fk_alerts_resolved_by_users")),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], name=op.f("fk_alerts_rule_id_alert_rules")),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_alerts_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_customer_id"), "alerts", ["customer_id"], unique=False)
    op.create_index(op.f("ix_alerts_reseller_id"), "alerts", ["reseller_id"], unique=False)
    op.create_index("ix_alerts_state_type", "alerts", ["state", "type"], unique=False)
    op.create_index(
        "uq_alerts_dedup_open",
        "alerts",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("state <> 'resolved'"),
    )
    op.create_table(
        "audit_log",
        sa.Column("reseller_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_audit_log_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_entity_entity_id", "audit_log", ["entity", "entity_id"], unique=False)
    op.create_index(
        "ix_audit_log_reseller_id_created_at",
        "audit_log",
        ["reseller_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "erp_tokens",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_prefix", sa.String(length=12), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_erp_tokens_created_by_users")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_erp_tokens_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_erp_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_erp_tokens_token_hash")),
    )
    op.create_index(op.f("ix_erp_tokens_reseller_id"), "erp_tokens", ["reseller_id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "read_profiles",
        sa.Column("profile_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_yaml", sa.Text(), nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_read_profiles_created_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_read_profiles")),
        sa.UniqueConstraint("profile_key", "version", name=op.f("uq_read_profiles_profile_key_version")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("created_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "snmp_credentials",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=8), nullable=False),
        sa.Column("community_enc", sa.LargeBinary(), nullable=True),
        sa.Column("v3_username", sa.String(length=128), nullable=True),
        sa.Column("v3_auth_protocol", sa.String(length=16), nullable=True),
        sa.Column("v3_auth_password_enc", sa.LargeBinary(), nullable=True),
        sa.Column("v3_priv_protocol", sa.String(length=16), nullable=True),
        sa.Column("v3_priv_password_enc", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "v3_auth_protocol IN ('SHA', 'SHA256')", name=op.f("ck_snmp_credentials_v3_auth_protocol_valid")
        ),
        sa.CheckConstraint(
            "v3_priv_protocol IN ('AES', 'AES256')", name=op.f("ck_snmp_credentials_v3_priv_protocol_valid")
        ),
        sa.CheckConstraint("version IN ('v1', 'v2c', 'v3')", name=op.f("ck_snmp_credentials_version_valid")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_snmp_credentials_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_snmp_credentials_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snmp_credentials")),
        sa.UniqueConstraint("site_id", "position", name=op.f("uq_snmp_credentials_site_id_position")),
    )
    op.create_index(
        op.f("ix_snmp_credentials_reseller_id"), "snmp_credentials", ["reseller_id"], unique=False
    )
    op.create_table(
        "agent_enrollment_codes",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_enrollment_codes_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_agent_enrollment_codes_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_agent_enrollment_codes_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_agent_enrollment_codes_site_id_sites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_enrollment_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_agent_enrollment_codes_code")),
    )
    op.create_index(
        op.f("ix_agent_enrollment_codes_agent_id"), "agent_enrollment_codes", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_enrollment_codes_reseller_id"), "agent_enrollment_codes", ["reseller_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_enrollment_codes_site_id"), "agent_enrollment_codes", ["site_id"], unique=False
    )
    op.create_table(
        "agent_heartbeats",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("queue_pending", sa.Integer(), nullable=True),
        sa.Column("uptime_seconds", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("cluster_role", sa.String(length=16), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "channel IN ('ws', 'http', 'watchdog')", name=op.f("ck_agent_heartbeats_channel_valid")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_heartbeats_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_agent_heartbeats_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", "ts", name=op.f("pk_agent_heartbeats")),
        postgresql_partition_by="RANGE (ts)",
    )
    op.create_index(
        "ix_agent_heartbeats_agent_id_ts",
        "agent_heartbeats",
        ["agent_id", sa.literal_column("ts DESC")],
        unique=False,
    )
    op.create_table(
        "cluster_events",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("from_agent_id", sa.UUID(), nullable=True),
        sa.Column("to_agent_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cluster_events_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["from_agent_id"], ["agents.id"], name=op.f("fk_cluster_events_from_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_cluster_events_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_cluster_events_site_id_sites")),
        sa.ForeignKeyConstraint(
            ["to_agent_id"], ["agents.id"], name=op.f("fk_cluster_events_to_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_events")),
    )
    op.create_index(op.f("ix_cluster_events_reseller_id"), "cluster_events", ["reseller_id"], unique=False)
    op.create_index(op.f("ix_cluster_events_site_id"), "cluster_events", ["site_id"], unique=False)
    op.create_table(
        "commands",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("target", sa.String(length=16), server_default=sa.text("'agent'"), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("progress", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'sent', 'acked', 'running', 'succeeded', 'failed', 'expired', 'cancelled')",
            name=op.f("ck_commands_state_valid"),
        ),
        sa.CheckConstraint("target IN ('agent', 'watchdog')", name=op.f("ck_commands_target_valid")),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_commands_agent_id_agents")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_commands_created_by_users")),
        sa.ForeignKeyConstraint(["parent_id"], ["commands.id"], name=op.f("fk_commands_parent_id_commands")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_commands_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commands")),
    )
    op.create_index("ix_commands_agent_id_state", "commands", ["agent_id", "state"], unique=False)
    op.create_index(op.f("ix_commands_reseller_id"), "commands", ["reseller_id"], unique=False)
    op.create_index("ix_commands_state_expires_at", "commands", ["state", "expires_at"], unique=False)
    op.create_table(
        "ip_ranges",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("cidr", sa.String(length=64), nullable=True),
        sa.Column("start_ip", sa.String(length=64), nullable=True),
        sa.Column("end_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "exclusions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'approved'"), nullable=False),
        sa.Column("suggested_by_agent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('approved', 'suggested')", name=op.f("ck_ip_ranges_status_valid")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_ip_ranges_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_ip_ranges_site_id_sites")),
        sa.ForeignKeyConstraint(
            ["suggested_by_agent_id"], ["agents.id"], name=op.f("fk_ip_ranges_suggested_by_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ip_ranges")),
    )
    op.create_index(op.f("ix_ip_ranges_reseller_id"), "ip_ranges", ["reseller_id"], unique=False)
    op.create_index(op.f("ix_ip_ranges_site_id"), "ip_ranges", ["site_id"], unique=False)
    op.create_table(
        "models",
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sys_object_id_prefix", sa.String(length=128), nullable=True),
        sa.Column("is_color", sa.Boolean(), nullable=True),
        sa.Column("max_paper", sa.String(length=4), nullable=True),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("max_paper IN ('A4', 'A3')", name=op.f("ck_models_max_paper_valid")),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], name=op.f("fk_models_brand_id_brands")),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["read_profiles.id"], name=op.f("fk_models_profile_id_read_profiles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("brand_id", "name", name=op.f("uq_models_brand_id_name")),
    )
    op.create_table(
        "notifications",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=True),
        sa.Column("alert_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("destination", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed', 'suppressed')",
            name=op.f("ck_notifications_status_valid"),
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], name=op.f("fk_notifications_alert_id_alerts")),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channels.id"],
            name=op.f("fk_notifications_channel_id_notification_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_notifications_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_alert_id"), "notifications", ["alert_id"], unique=False)
    op.create_index(op.f("ix_notifications_reseller_id"), "notifications", ["reseller_id"], unique=False)
    op.create_index(
        "ix_notifications_status_next_attempt_at",
        "notifications",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "agent_logs",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("command_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source IN ('agent', 'watchdog')", name=op.f("ck_agent_logs_source_valid")),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_agent_logs_agent_id_agents")),
        sa.ForeignKeyConstraint(
            ["command_id"], ["commands.id"], name=op.f("fk_agent_logs_command_id_commands")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_agent_logs_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_logs")),
    )
    op.create_index(op.f("ix_agent_logs_agent_id"), "agent_logs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_logs_reseller_id"), "agent_logs", ["reseller_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("serial", sa.String(length=128), nullable=False),
        sa.Column("mac", sa.String(length=32), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("sys_object_id", sa.String(length=128), nullable=True),
        sa.Column("sys_descr", sa.Text(), nullable=True),
        sa.Column("firmware", sa.String(length=200), nullable=True),
        sa.Column("asset_tag", sa.String(length=100), nullable=True),
        sa.Column("sector", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_color", sa.Boolean(), nullable=True),
        sa.Column("profile_key", sa.String(length=100), nullable=True),
        sa.Column("counter_source", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=16), server_default=sa.text("'snmp'"), nullable=False),
        sa.Column("usb_agent_id", sa.UUID(), nullable=True),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("last_status_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_bits", sa.Integer(), nullable=True),
        sa.Column(
            "last_error_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_panel_text", sa.Text(), nullable=True),
        sa.Column("last_total", sa.BigInteger(), nullable=True),
        sa.Column("last_mono", sa.BigInteger(), nullable=True),
        sa.Column("last_color", sa.BigInteger(), nullable=True),
        sa.Column("disconnected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("monitored", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_agent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "last_status IN ('ready', 'printing', 'warmup', 'energy_saving', 'warning', 'error', 'offline', 'unknown')",
            name=op.f("ck_devices_last_status_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('snmp', 'http', 'usb', 'manual')", name=op.f("ck_devices_source_valid")
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], name=op.f("fk_devices_brand_id_brands")),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_devices_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["last_agent_id"], ["agents.id"], name=op.f("fk_devices_last_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], name=op.f("fk_devices_model_id_models")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_devices_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_devices_site_id_sites")),
        sa.ForeignKeyConstraint(["usb_agent_id"], ["agents.id"], name=op.f("fk_devices_usb_agent_id_agents")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("reseller_id", "serial", name=op.f("uq_devices_reseller_id_serial")),
    )
    op.create_index(op.f("ix_devices_customer_id"), "devices", ["customer_id"], unique=False)
    op.create_index(op.f("ix_devices_reseller_id"), "devices", ["reseller_id"], unique=False)
    op.create_index(op.f("ix_devices_site_id"), "devices", ["site_id"], unique=False)
    op.create_index("ix_devices_site_id_ip", "devices", ["site_id", "ip"], unique=False)
    op.create_table(
        "device_events",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type IN ('discovered', 'ip_changed', 'moved_site', 'replaced', 'counter_regression', 'reactivated', 'deactivated', 'manual_adjust', 'read_failed', 'suspicious_jump', 'sum_mismatch', 'reading_discarded', 'reading_classified')",
            name=op.f("ck_device_events_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_device_events_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_device_events_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_device_events_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_events")),
    )
    op.create_index(
        "ix_device_events_device_id_created_at",
        "device_events",
        ["device_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_device_events_reseller_id"), "device_events", ["reseller_id"], unique=False)
    op.create_table(
        "mib_walks",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("command_id", sa.UUID(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("root_oid", sa.String(length=255), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("oid_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_mib_walks_agent_id_agents")),
        sa.ForeignKeyConstraint(
            ["command_id"], ["commands.id"], name=op.f("fk_mib_walks_command_id_commands")
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_mib_walks_created_by_users")),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], name=op.f("fk_mib_walks_device_id_devices")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_mib_walks_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mib_walks")),
    )
    op.create_index(op.f("ix_mib_walks_device_id"), "mib_walks", ["device_id"], unique=False)
    op.create_index(op.f("ix_mib_walks_reseller_id"), "mib_walks", ["reseller_id"], unique=False)
    op.create_table(
        "reading_discards",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_reading_discards_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_reading_discards_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_reading_discards_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_discards")),
    )
    op.create_index(op.f("ix_reading_discards_device_id"), "reading_discards", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_reading_discards_reseller_id"), "reading_discards", ["reseller_id"], unique=False
    )
    op.create_table(
        "readings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=True),
        sa.Column("mono", sa.BigInteger(), nullable=True),
        sa.Column("color", sa.BigInteger(), nullable=True),
        sa.Column("mono_large", sa.BigInteger(), nullable=True),
        sa.Column("color_large", sa.BigInteger(), nullable=True),
        sa.Column("copy_mono", sa.BigInteger(), nullable=True),
        sa.Column("copy_color", sa.BigInteger(), nullable=True),
        sa.Column("print_mono", sa.BigInteger(), nullable=True),
        sa.Column("print_color", sa.BigInteger(), nullable=True),
        sa.Column("scan", sa.BigInteger(), nullable=True),
        sa.Column("fax", sa.BigInteger(), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("error_bits", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=16), server_default=sa.text("'snmp'"), nullable=False),
        sa.Column("profile_key", sa.String(length=100), nullable=True),
        sa.Column("counter_source", sa.String(length=64), nullable=True),
        sa.Column(
            "flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('snmp', 'http', 'usb', 'manual')", name=op.f("ck_readings_source_valid")
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_readings_agent_id_agents")),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], name=op.f("fk_readings_device_id_devices")),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_readings_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_readings_user_id_users")),
        sa.PrimaryKeyConstraint("id", "read_at", name=op.f("pk_readings")),
        postgresql_partition_by="RANGE (read_at)",
    )
    op.create_index(
        "ix_readings_device_id_read_at",
        "readings",
        ["device_id", sa.literal_column("read_at DESC")],
        unique=False,
    )
    op.create_index("ix_readings_reseller_id_read_at", "readings", ["reseller_id", "read_at"], unique=False)
    op.create_table(
        "supplies_current",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("supply_key", sa.String(length=100), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("supply_type", sa.String(length=32), nullable=True),
        sa.Column("supply_class", sa.String(length=16), server_default=sa.text("'consumed'"), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("max_capacity", sa.Integer(), nullable=True),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("level_state", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("days_to_empty", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("forecast_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "level_state IN ('ok', 'unknown', 'some_remaining')",
            name=op.f("ck_supplies_current_level_state_valid"),
        ),
        sa.CheckConstraint(
            "supply_class IN ('consumed', 'receptacle', 'other')",
            name=op.f("ck_supplies_current_supply_class_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_supplies_current_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_supplies_current_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("device_id", "supply_key", name=op.f("pk_supplies_current")),
    )
    op.create_index(
        op.f("ix_supplies_current_reseller_id"), "supplies_current", ["reseller_id"], unique=False
    )
    op.create_table(
        "supply_readings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("supply_key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("supply_type", sa.String(length=32), nullable=True),
        sa.Column("supply_class", sa.String(length=16), server_default=sa.text("'consumed'"), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("max_capacity", sa.Integer(), nullable=True),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("level_state", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "level_state IN ('ok', 'unknown', 'some_remaining')",
            name=op.f("ck_supply_readings_level_state_valid"),
        ),
        sa.CheckConstraint(
            "supply_class IN ('consumed', 'receptacle', 'other')",
            name=op.f("ck_supply_readings_supply_class_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_supply_readings_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_supply_readings_reseller_id_resellers")
        ),
        sa.PrimaryKeyConstraint("id", "read_at", name=op.f("pk_supply_readings")),
        postgresql_partition_by="RANGE (read_at)",
    )
    op.create_index(
        "ix_supply_readings_device_id_supply_key_read_at",
        "supply_readings",
        ["device_id", "supply_key", "read_at"],
        unique=False,
    )
    op.create_table(
        "reading_adjustments",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("reading_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=True),
        sa.Column("mono", sa.BigInteger(), nullable=True),
        sa.Column("color", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_reading_adjustments_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["reading_id", "read_at"],
            ["readings.id", "readings.read_at"],
            name=op.f("fk_reading_adjustments_reading_id_readings"),
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_reading_adjustments_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reading_adjustments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_adjustments")),
    )
    op.create_index(
        "ix_reading_adjustments_device_id_created_at",
        "reading_adjustments",
        ["device_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_adjustments_reseller_id"), "reading_adjustments", ["reseller_id"], unique=False
    )
    op.create_table(
        "reading_reviews",
        sa.Column("reseller_id", sa.UUID(), nullable=False),
        sa.Column("reading_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "classification IN ('board_replacement', 'read_error', 'valid')",
            name=op.f("ck_reading_reviews_classification_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["reading_id", "read_at"],
            ["readings.id", "readings.read_at"],
            name=op.f("fk_reading_reviews_reading_id_readings"),
        ),
        sa.ForeignKeyConstraint(
            ["reseller_id"], ["resellers.id"], name=op.f("fk_reading_reviews_reseller_id_resellers")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reading_reviews_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_reviews")),
    )
    op.create_index(op.f("ix_reading_reviews_reseller_id"), "reading_reviews", ["reseller_id"], unique=False)
    op.create_index("uq_reading_reviews_reading", "reading_reviews", ["reading_id"], unique=True)
    # ### end Alembic commands ###
    _upgrade_sql()


def downgrade() -> None:
    _downgrade_sql()
    op.drop_constraint("fk_sites_preferred_master_agent_id_agents", "sites", type_="foreignkey")
    op.drop_constraint("fk_sites_master_agent_id_agents", "sites", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_reading_reviews_reading", table_name="reading_reviews")
    op.drop_index(op.f("ix_reading_reviews_reseller_id"), table_name="reading_reviews")
    op.drop_table("reading_reviews")
    op.drop_index(op.f("ix_reading_adjustments_reseller_id"), table_name="reading_adjustments")
    op.drop_index("ix_reading_adjustments_device_id_created_at", table_name="reading_adjustments")
    op.drop_table("reading_adjustments")
    op.drop_index("ix_supply_readings_device_id_supply_key_read_at", table_name="supply_readings")
    op.drop_table("supply_readings")
    op.drop_index(op.f("ix_supplies_current_reseller_id"), table_name="supplies_current")
    op.drop_table("supplies_current")
    op.drop_index("ix_readings_reseller_id_read_at", table_name="readings")
    op.drop_index("ix_readings_device_id_read_at", table_name="readings")
    op.drop_table("readings")
    op.drop_index(op.f("ix_reading_discards_reseller_id"), table_name="reading_discards")
    op.drop_index(op.f("ix_reading_discards_device_id"), table_name="reading_discards")
    op.drop_table("reading_discards")
    op.drop_index(op.f("ix_mib_walks_reseller_id"), table_name="mib_walks")
    op.drop_index(op.f("ix_mib_walks_device_id"), table_name="mib_walks")
    op.drop_table("mib_walks")
    op.drop_index(op.f("ix_device_events_reseller_id"), table_name="device_events")
    op.drop_index("ix_device_events_device_id_created_at", table_name="device_events")
    op.drop_table("device_events")
    op.drop_index("ix_devices_site_id_ip", table_name="devices")
    op.drop_index(op.f("ix_devices_site_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_reseller_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_customer_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_agent_logs_reseller_id"), table_name="agent_logs")
    op.drop_index(op.f("ix_agent_logs_agent_id"), table_name="agent_logs")
    op.drop_table("agent_logs")
    op.drop_index("ix_notifications_status_next_attempt_at", table_name="notifications")
    op.drop_index(op.f("ix_notifications_reseller_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_alert_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("models")
    op.drop_index(op.f("ix_ip_ranges_site_id"), table_name="ip_ranges")
    op.drop_index(op.f("ix_ip_ranges_reseller_id"), table_name="ip_ranges")
    op.drop_table("ip_ranges")
    op.drop_index("ix_commands_state_expires_at", table_name="commands")
    op.drop_index(op.f("ix_commands_reseller_id"), table_name="commands")
    op.drop_index("ix_commands_agent_id_state", table_name="commands")
    op.drop_table("commands")
    op.drop_index(op.f("ix_cluster_events_site_id"), table_name="cluster_events")
    op.drop_index(op.f("ix_cluster_events_reseller_id"), table_name="cluster_events")
    op.drop_table("cluster_events")
    op.drop_index("ix_agent_heartbeats_agent_id_ts", table_name="agent_heartbeats")
    op.drop_table("agent_heartbeats")
    op.drop_index(op.f("ix_agent_enrollment_codes_site_id"), table_name="agent_enrollment_codes")
    op.drop_index(op.f("ix_agent_enrollment_codes_reseller_id"), table_name="agent_enrollment_codes")
    op.drop_index(op.f("ix_agent_enrollment_codes_agent_id"), table_name="agent_enrollment_codes")
    op.drop_table("agent_enrollment_codes")
    op.drop_index(op.f("ix_snmp_credentials_reseller_id"), table_name="snmp_credentials")
    op.drop_table("snmp_credentials")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("read_profiles")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_erp_tokens_reseller_id"), table_name="erp_tokens")
    op.drop_table("erp_tokens")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_reseller_id_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity_entity_id", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(
        "uq_alerts_dedup_open", table_name="alerts", postgresql_where=sa.text("state <> 'resolved'")
    )
    op.drop_index("ix_alerts_state_type", table_name="alerts")
    op.drop_index(op.f("ix_alerts_reseller_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_customer_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_agents_site_id_cluster_role", table_name="agents")
    op.drop_index(op.f("ix_agents_reseller_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("agent_releases")
    op.drop_index("uq_users_email_active", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index(op.f("ix_users_reseller_id"), table_name="users")
    op.drop_index(op.f("ix_users_customer_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sites_reseller_id"), table_name="sites")
    op.drop_index(op.f("ix_sites_customer_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_alert_rules_reseller_id"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_customer_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(
        "uq_customers_reseller_erp_code",
        table_name="customers",
        postgresql_where=sa.text("erp_code IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_customers_reseller_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_company_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("settings")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_notification_channels_reseller_id"), table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_index(op.f("ix_companies_reseller_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("roles")
    op.drop_table("resellers")
    op.drop_table("reading_idempotency")
    op.drop_table("brands")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS dm_ensure_month_partition(text, text, date)")
    op.execute("DROP FUNCTION IF EXISTS dm_block_modification()")


_APPEND_ONLY = ("readings", "audit_log")
_PARTITIONED = (("readings", "read_at"), ("supply_readings", "read_at"), ("agent_heartbeats", "ts"))

_BLOCK_FUNCTION_SQL = r"""
-- Bloqueia UPDATE/DELETE/TRUNCATE em tabelas somente-inserção (R6). A manutenção de partições
-- (mover linhas da partição default) liga dati.maintenance só dentro da própria transação.
CREATE OR REPLACE FUNCTION dm_block_modification() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF coalesce(current_setting('dati.maintenance', true), '') = 'on' THEN
        IF TG_LEVEL = 'STATEMENT' THEN RETURN NULL; END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'A tabela % é somente inserção: % não é permitido', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;

"""

_PARTITION_FUNCTION_SQL = r"""
-- Cria (se não existir) a partição mensal de `parent` que começa em `month_start`.
-- Linhas que caíram na partição default nesse intervalo são movidas antes do ATTACH,
-- então nenhuma leitura se perde mesmo se chegar antes de a partição existir.
CREATE OR REPLACE FUNCTION dm_ensure_month_partition(parent text, key_column text, month_start date)
RETURNS boolean
LANGUAGE plpgsql AS $$
DECLARE
    first_day date := date_trunc('month', month_start)::date;
    next_day date := (date_trunc('month', month_start) + interval '1 month')::date;
    part text := parent || '_' || to_char(first_day, 'YYYY_MM');
    def text := parent || '_default';
    -- Limites sempre em UTC explícito, independentemente do fuso da sessão.
    lo text := to_char(first_day, 'YYYY-MM-DD') || ' 00:00:00+00';
    hi text := to_char(next_day, 'YYYY-MM-DD') || ' 00:00:00+00';
BEGIN
    IF to_regclass(part) IS NOT NULL THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TABLE %I (LIKE %I INCLUDING DEFAULTS INCLUDING CONSTRAINTS)', part, parent);
    IF to_regclass(def) IS NOT NULL THEN
        PERFORM set_config('dati.maintenance', 'on', true);
        EXECUTE format(
            'WITH moved AS (DELETE FROM %I WHERE %I >= %L AND %I < %L RETURNING *) INSERT INTO %I SELECT * FROM moved',
            def, key_column, lo, key_column, hi, part
        );
        PERFORM set_config('dati.maintenance', 'off', true);
    END IF;
    EXECUTE format('ALTER TABLE %I ATTACH PARTITION %I FOR VALUES FROM (%L) TO (%L)', parent, part, lo, hi);
    IF parent IN ('readings', 'audit_log') THEN
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()',
            part || '_no_truncate', part
        );
    END IF;
    RETURN true;
END;
$$;
"""


def _upgrade_sql() -> None:
    op.execute(_BLOCK_FUNCTION_SQL)
    op.execute(_PARTITION_FUNCTION_SQL)
    for table in _APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION dm_block_modification()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()"
        )
    for table, column in _PARTITIONED:
        op.execute(f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT")
        if table in _APPEND_ONLY:
            op.execute(
                f"CREATE TRIGGER {table}_default_no_truncate BEFORE TRUNCATE ON {table}_default "
                "FOR EACH STATEMENT EXECUTE FUNCTION dm_block_modification()"
            )
        # Mês anterior, atual e os 3 próximos; o worker mantém a janela andando (job diário).
        op.execute(
            f"SELECT dm_ensure_month_partition('{table}', '{column}', "
            "(date_trunc('month', now()) + make_interval(months => m))::date) "
            "FROM generate_series(-1, 3) AS m"
        )


def _downgrade_sql() -> None:
    for table in _APPEND_ONLY:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
