"""fase 7 acesso web

Revision ID: 8fa8ef64d498
Revises: d1a9a86b0475
Create Date: 2026-09-29 17:27:53.257820+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8fa8ef64d498'
down_revision: str | None = 'd1a9a86b0475'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_sessions',
    sa.Column('reseller_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(length=8), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requests', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_web_sessions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], name=op.f('fk_web_sessions_command_id_commands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_web_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], name=op.f('fk_web_sessions_reseller_id_resellers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_web_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_web_sessions_token_hash'))
    )
    op.create_index('ix_web_sessions_reseller_id_created_at', 'web_sessions', ['reseller_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_web_sessions_reseller_id_created_at', table_name='web_sessions')
    op.drop_table('web_sessions')
    # ### end Alembic commands ###
