"""fase 7 perfis

Revision ID: 66d59dd070b4
Revises: 5822467356bf
Create Date: 2026-09-29 16:36:59.601284+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '66d59dd070b4'
down_revision: str | None = '5822467356bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read_profiles', sa.Column('source', sa.String(length=16), server_default=sa.text("'file'"), nullable=False))
    op.add_column('read_profiles', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint("source_valid", "read_profiles", "source IN ('file', 'portal')")
    # Porta SNMP do walk: o teste de rascunho do perfil lê o mesmo equipamento (simulador/NAT usam outras portas).
    op.add_column("mib_walks", sa.Column("port", sa.Integer(), nullable=True))


def downgrade() -> None:
    op.drop_column("mib_walks", "port")
    op.drop_constraint(op.f("ck_read_profiles_source_valid"), "read_profiles", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('read_profiles', 'notes')
    op.drop_column('read_profiles', 'source')
    # ### end Alembic commands ###
