"""fase 6 alertas

Revision ID: 5822467356bf
Revises: 11f512d72613
Create Date: 2026-09-29 13:16:22.728467+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5822467356bf'
down_revision: str | None = '11f512d72613'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Alertas que já existiam não geram notificação retroativa.
    op.execute("UPDATE alerts SET notified_at = now() WHERE notified_at IS NULL")
    op.create_index(
        "ix_alerts_pending_notification",
        "alerts",
        ["opened_at"],
        postgresql_where=sa.text("notified_at IS NULL"),
    )
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open', 'jam_recurrent', 'printer_alert')")


def downgrade() -> None:
    op.execute("DELETE FROM alert_rules WHERE type IN ('jam_recurrent', 'printer_alert')")
    op.drop_constraint(op.f("ck_alert_rules_type_valid"), "alert_rules", type_="check")
    op.create_check_constraint("type_valid", "alert_rules", "type IN ('toner_low', 'toner_days_left', 'device_no_reading', 'agent_offline', 'counter_regression', 'suspicious_jump', 'sum_mismatch', 'hardware_error', 'paper_jam', 'door_open')")
    op.drop_index("ix_alerts_pending_notification", table_name="alerts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'notified_at')
    # ### end Alembic commands ###
