"""fase 2: portas snmp e idempotencia de itens

Revision ID: 234558d95f9a
Revises: aadbb17b4720
Create Date: 2026-09-24 18:45:48.618747+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '234558d95f9a'
down_revision: str | None = 'aadbb17b4720'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('snmp_port', sa.Integer(), server_default=sa.text('161'), nullable=False))
    op.add_column('ip_ranges', sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[161]'::jsonb"), nullable=False))
    op.add_column('reading_idempotency', sa.Column('kind', sa.String(length=16), server_default=sa.text("'reading'"), nullable=False))
    op.add_column('reading_idempotency', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.add_column('reading_idempotency', sa.Column('result', sa.String(length=16), server_default=sa.text("'accepted'"), nullable=False))
    op.alter_column('reading_idempotency', 'reading_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_reading_idempotency_agent_id_agents'), 'reading_idempotency', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###
    # Linhas do tempo com ordem estável mesmo dentro da mesma transação.
    for table in ("device_events", "audit_log"):
        op.alter_column(table, "created_at", server_default=sa.text("clock_timestamp()"))


def downgrade() -> None:
    for table in ("device_events", "audit_log"):
        op.alter_column(table, "created_at", server_default=sa.text("now()"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reading_idempotency_agent_id_agents'), 'reading_idempotency', type_='foreignkey')
    op.alter_column('reading_idempotency', 'reading_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reading_idempotency', 'result')
    op.drop_column('reading_idempotency', 'agent_id')
    op.drop_column('reading_idempotency', 'kind')
    op.drop_column('ip_ranges', 'ports')
    op.drop_column('devices', 'snmp_port')
    # ### end Alembic commands ###
