"""fase 7 fila do erp

Revision ID: d1a9a86b0475
Revises: 66d59dd070b4
Create Date: 2026-09-29 17:13:41.030898+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd1a9a86b0475'
down_revision: str | None = '66d59dd070b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_queue',
    sa.Column('reseller_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_via', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('counters', 'supply_request', 'service_order')", name=op.f('ck_erp_queue_kind_valid')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'error')", name=op.f('ck_erp_queue_status_valid')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_erp_queue_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_erp_queue_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], name=op.f('fk_erp_queue_reseller_id_resellers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_queue')),
    sa.UniqueConstraint('reseller_id', 'dedup_key', name=op.f('uq_erp_queue_reseller_id_dedup_key'))
    )
    op.create_index('ix_erp_queue_due', 'erp_queue', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_erp_queue_reseller_id_created_at', 'erp_queue', ['reseller_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_erp_queue_reseller_id_created_at', table_name='erp_queue')
    op.drop_index('ix_erp_queue_due', table_name='erp_queue', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('erp_queue')
    # ### end Alembic commands ###
