"""fase 3 presenca e pausa

Revision ID: 88bc5dd48678
Revises: 234558d95f9a
Create Date: 2026-09-25 13:35:10.317957+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '88bc5dd48678'
down_revision: str | None = '234558d95f9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_presence',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('reseller_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.String(length=64), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_presence_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], name=op.f('fk_agent_presence_reseller_id_resellers')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agent_presence'))
    )
    op.create_index(op.f('ix_agent_presence_reseller_id'), 'agent_presence', ['reseller_id'], unique=False)
    op.add_column('agents', sa.Column('paused', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    # A configuração do agente ganhou ws_url e a pausa do servidor: coletores já instalados precisam
    # baixá-la de novo (senão continuam com a cópia antiga em cache, sem o endereço do WebSocket).
    op.execute("UPDATE agents SET config_version = config_version + 1")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'paused')
    op.drop_index(op.f('ix_agent_presence_reseller_id'), table_name='agent_presence')
    op.drop_table('agent_presence')
    # ### end Alembic commands ###
